workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    max_build_duration: 45
    environment:
      android_sdk_version: 35
      vars:
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD

    scripts:
      - name: Gradle Clean & Build
        script: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew assembleRelease

    artifacts:
      - path: app/build/outputs/apk/release/app-release.apk
        name: VirtualOutfitTryOn.apk

    publishing:
      email:
        recipients:
          - shivkadari@gmail.com
